// <auto-generated />
using System;
using BinanceBot.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BinanceBot.Infrastructure.Migrations
{
    [DbContext(typeof(BotDbContext))]
    partial class BotDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BinanceBot.Infrastructure.Persistence.Entities.BotStateEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActiveStrategy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("BtcBalance")
                        .HasColumnType("numeric(18,8)");

                    b.Property<decimal>("EurBalance")
                        .HasColumnType("numeric(18,8)");

                    b.Property<decimal>("InitialBalanceEur")
                        .HasColumnType("numeric(18,8)");

                    b.Property<decimal>("Last24hHighPrice")
                        .HasColumnType("numeric(18,8)");

                    b.Property<decimal>("Last24hLowPrice")
                        .HasColumnType("numeric(18,8)");

                    b.Property<DateTime?>("Last24hPriceTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastRebalanceTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("LastTradePrice")
                        .HasColumnType("numeric(18,8)");

                    b.Property<string>("RunState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StrategyStateJson")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BotState", (string)null);
                });

            modelBuilder.Entity("BinanceBot.Infrastructure.Persistence.Entities.TradeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Fee")
                        .HasColumnType("numeric(18,8)");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(18,8)");

                    b.Property<decimal>("QuantityBtc")
                        .HasColumnType("numeric(18,8)");

                    b.Property<decimal>("QuoteAmountEur")
                        .HasColumnType("numeric(18,8)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StrategyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.ToTable("Trades", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
